### ISSUE TITLE
Dataset Extraction Issue

### ISSUE THREAD

**Issue by debasmitdas** [xiaoqian-shen/StoryGPT-V#2]
Hi ! I was trying to run training and inference using the Flintstones dataset. For that, we need to extract 'flintstones.zip'. In that directory, we try to extract 'video_frames_sampled_4x.zip'. However, when we try to extract it, we produce an error:

`             
ERRORS:
Unexpected end of archive

Path = video_frames_sampled_4x.zip
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 1472103293

ERROR: Data Error : video_frames_sampled_4x/s_02_e_13_shot_035614_035688.npy
                                                                   
Sub items Errors: 1

Archives with Errors: 1

Open Errors: 1

Sub items Errors: 1
` 

Could you help us figure it out or produce a fresh zip file ?

**Comment by xiaoqian-shen** [comment]
Thanks for raising this issue. We will try to find the problem and upload a new one soon. In case of urgency, you can also obtain the dataset from this [repo](https://github.com/xichenpan/ARLDM) and use superresolution model [CompVis/ldm-super-resolution-4x-openimages](https://huggingface.co/CompVis/ldm-super-resolution-4x-openimages) to get the 4x version.

**Comment by xiaoqian-shen** [comment]
I have updated the zip file [download](https://storygpt-v.s3.amazonaws.com/data/flintstones.zip). Please check whether the issue has been solved.
